In [10]:
import pandas as pd
df=pd.read_csv("bank-additional-full.csv")

In [11]:
print(df)

      age;"job";"marital";"education";"default";"housing";"loan";"contact";"month";"day_of_week";"duration";"campaign";"pdays";"previous";"poutcome";"emp.var.rate";"cons.price.idx";"cons.conf.idx";"euribor3m";"nr.employed";"y"
0      56;"housemaid";"married";"basic.4y";"no";"no";...
1      57;"services";"married";"high.school";"unknown...
2      37;"services";"married";"high.school";"no";"ye...
3      40;"admin.";"married";"basic.6y";"no";"no";"no...
4      56;"services";"married";"high.school";"no";"no...
...                                                  ...
41183  73;"retired";"married";"professional.course";"...
41184  46;"blue-collar";"married";"professional.cours...
41185  56;"retired";"married";"university.degree";"no...
41186  44;"technician";"married";"professional.course...
41187  74;"retired";"married";"professional.course";"...

[41188 rows x 1 columns]

In [12]:
data=pd.read_csv("bank-additional-full.csv", sep=";",usecols=["age","job"])

In [13]:
print(data)

       age          job
0       56    housemaid
1       57     services
2       37     services
3       40       admin.
4       56     services
...    ...          ...
41183   73      retired
41184   46  blue-collar
41185   56      retired
41186   44   technician
41187   74      retired

[41188 rows x 2 columns]

In [14]:
new=pd.read_csv("bank-additional-full.csv", sep=";",usecols=["age","job"],index_col="age")
print(new)

             job
age
56     housemaid
57      services
37      services
40        admin.
56      services
..           ...
73       retired
46   blue-collar
56       retired
44    technician
74       retired

[41188 rows x 1 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                        Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                        --------------  -----
 0   age;"job";"marital";"education";"default";"housing";"loan";"contact";"month";"day_of_week";"duration";"campaign";"pdays";"previous";"poutcome";"emp.var.rate";"cons.price.idx";"cons.conf.idx";"euribor3m";"nr.employed";"y"  41188 non-null  object
dtypes: object(1)
memory usage: 321.9+ KB

In [16]:
df.columns

Index(['age;"job";"marital";"education";"default";"housing";"loan";"contact";"month";"day_of_week";"duration";"campaign";"pdays";"previous";"poutcome";"emp.var.rate";"cons.price.idx";"cons.conf.idx";"euribor3m";"nr.employed";"y"'], dtype='object')

In [17]:
print(data[data["age"]>30])

       age          job
0       56    housemaid
1       57     services
2       37     services
3       40       admin.
4       56     services
...    ...          ...
41183   73      retired
41184   46  blue-collar
41185   56      retired
41186   44   technician
41187   74      retired

[33805 rows x 2 columns]

In [18]:
data.describe()

               age
count  41188.00000
mean      40.02406
std       10.42125
min       17.00000
25%       32.00000
50%       38.00000
75%       47.00000
max       98.00000

In [19]:
data.tail()

       age          job
41183   73      retired
41184   46  blue-collar
41185   56      retired
41186   44   technician
41187   74      retired

In [20]:
dataset=pd.read_csv("bank-additional-full.csv",sep=";",usecols=["age"],index_col=None)
print(dataset.describe())
print(dataset.info())
print(dataset.max())
print(dataset.mean())

               age
count  41188.00000
mean      40.02406
std       10.42125
min       17.00000
25%       32.00000
50%       38.00000
75%       47.00000
max       98.00000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     41188 non-null  int64
dtypes: int64(1)
memory usage: 321.9 KB
None
age    98
dtype: int64
age    40.02406
dtype: float64

In [21]:
#label encoding
data=pd.read_csv("bank-additional-full.csv",sep=";")
data['y']=data['y'].map({'no':0,'yes':1})
print(data['y'])

0        0
1        0
2        0
3        0
4        0
        ..
41183    1
41184    0
41185    0
41186    1
41187    0
Name: y, Length: 41188, dtype: int64

In [22]:
allcols=data.select_dtypes(include=['object']).columns
print(allcols)

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'day_of_week', 'poutcome'],
      dtype='object')

In [ ]:
#one hot encoding
data1 = pd.get_dummies(data, drop_first=True)
print(data1.head())

In [ ]:
print(data1.filter(like="marital").head())

In [ ]:
import pandas as pd

In [ ]:
ycol=data1['y']
print(ycol)

In [ ]:
ycol=data['age'].mode()[0]
print(ycol)